### ISSUE TITLE
P2P c ode review

### ISSUE THREAD

**Issue by nyatindopatrick** [nyatindopatrick/the-news-week-clone#5]
Please leave comments and suggestions.

**Comment by nyatindopatrick** [comment]
The subscribe button should have space from the right margin. 
Try adding some margin-right to the button
![Screenshot from 2020-07-28 09-18-42](https://user-images.githubusercontent.com/48393059/88626478-5d399680-d0b3-11ea-8cff-97d75e9000a1.png)

**Comment by GraceMwende** [comment]
Html and Css at work,awesome
hoping to do such too
